### PR TITLE
Fix for passing data to gocmdpev

### PR DESCRIPTION
**Pull request by lgromanowski**
If query data contains characters which can be interpreted by shell (ie. single quotes, or double quotes) then system call in gocmdpev method will be broken and it will return an error. Better way will be storing query data in temporary file and than cating it to gocmdpev (instead of echoing a string).

### CODE REVIEW

**Comment by lgromanowski** [comment]
@bradurani would you merge this PR?

**Review by bradurani — APPROVED** [review]
Thank you! Happy Hacktoberfest!

**Comment by bradurani** [comment]
I've published this to RubyGems FYI: https://rubygems.org/gems/pg-eyeballs

**Comment by lgromanowski** [comment]
Thanks! :)

**Pull request merged**
